version: '3.8'

services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped